version: "3.9"

name: ss-infra

services:

  snippet-db:
    image: postgres:16-alpine
    container_name: snippet-db
    env_file: [.env]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [ss-dev]


  snippet-service:
    image: ghcr.io/ingenieria-de-sistemas-123/snippet-service:latest
    container_name: snippet-service
    depends_on:
      snippet-db:
        condition: service_healthy
    env_file: [.env]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports: ["8081:8081"]
    networks: [ss-dev]


  language-service:
    image: ghcr.io/ingenieria-de-sistemas-123/language-service:latest
    container_name: language-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports: ["8082:8082"]
    networks: [ss-dev]

networks:
  ss-dev:

volumes:
  pg_data:
