name: "CD - DEV"

on:
  push:
    branches:
      - dev
jobs:
  deploy_to_vm:
    runs-on: ubuntu-latest
    steps:
      - name: docker compose config (dev)
        run: docker compose -f docker-compose.dev.yml config

      - name: Update service on VM with new image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            pwd
            cd infra
            git pull origin dev
            sudo echo ${{ secrets.GH_PAT }} | sudo docker login -u ${{ github.actor }} --password-stdin ghcr.io
            sudo docker compose -f docker-compose.dev.yml down
            sudo docker compose -f docker-compose.dev.yml pull
            sudo docker compose -f docker-compose.dev.yml up -d
            
